[2025-05-25T07:10:58.368+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T07:11:05.232+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-05-25T07:11:05.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-05-25T07:11:05.891+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T07:11:04.648+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): move_data_file> on 2025-04-13 00:00:00+00:00
[2025-05-25T07:11:05.157+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1662) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T07:11:05.282+0000] {standard_task_runner.py:72} INFO - Started process 1722 to run task
[2025-05-25T07:11:05.587+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'move_data_file', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpbkdw0k4n']
[2025-05-25T07:11:05.868+0000] {standard_task_runner.py:105} INFO - Job 238: Subtask move_data_file
[2025-05-25T07:11:07.384+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.move_data_file scheduled__2025-04-13T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T07:11:11.519+0000] {job.py:229} INFO - Heartbeat recovered after 14.35 seconds
[2025-05-25T07:11:13.722+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='move_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-05-25T07:11:13.774+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T07:11:14.722+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-25T07:11:15.224+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /tmp/processed_data/ && mv /tmp/data.csv /tmp/processed_data/']
[2025-05-25T07:11:17.372+0000] {subprocess.py:99} INFO - Output:
[2025-05-25T07:11:17.887+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-25T07:11:19.269+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T07:11:19.409+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=move_data_file, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250525T071105, end_date=20250525T071119
[2025-05-25T07:11:21.654+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T07:11:23.842+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T07:11:24.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
