[2025-05-25T07:06:58.387+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T07:07:00.683+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-25T07:07:01.559+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-05-25T07:07:01.574+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T07:07:04.456+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_file> on 2025-04-01 00:00:00+00:00
[2025-05-25T07:07:05.392+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1476) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T07:07:05.507+0000] {standard_task_runner.py:72} INFO - Started process 1515 to run task
[2025-05-25T07:07:05.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'generate_file', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmptp5geil3']
[2025-05-25T07:07:05.793+0000] {standard_task_runner.py:105} INFO - Job 211: Subtask generate_file
[2025-05-25T07:07:27.845+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.generate_file scheduled__2025-04-01T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T07:07:29.143+0000] {job.py:229} INFO - Heartbeat recovered after 34.45 seconds
[2025-05-25T07:07:32.774+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='generate_file' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-05-25T07:07:32.835+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T07:07:33.750+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-25T07:07:33.887+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T07:07:33.904+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=generate_file, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250525T070700, end_date=20250525T070733
[2025-05-25T07:07:34.598+0000] {job.py:229} INFO - Heartbeat recovered after 22.74 seconds
[2025-05-25T07:07:35.097+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T07:07:35.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
