[2025-05-25T05:18:48.460+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:18:49.199+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2024-12-19T00:00:00+00:00 [queued]>
[2025-05-25T05:18:49.674+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2024-12-19T00:00:00+00:00 [queued]>
[2025-05-25T05:18:49.691+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:18:50.447+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_file> on 2024-12-19 00:00:00+00:00
[2025-05-25T05:18:51.935+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'generate_file', 'scheduled__2024-12-19T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmp6xa8lwkp']
[2025-05-25T05:18:52.449+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask generate_file
[2025-05-25T05:18:51.602+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=329) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:18:52.680+0000] {standard_task_runner.py:72} INFO - Started process 368 to run task
[2025-05-25T05:18:58.494+0000] {job.py:229} INFO - Heartbeat recovered after 14.11 seconds
[2025-05-25T05:19:06.968+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.generate_file scheduled__2024-12-19T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:19:11.310+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='generate_file' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-19T00:00:00+00:00'
[2025-05-25T05:19:11.315+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:19:11.868+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-25T05:19:11.969+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:19:11.974+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=generate_file, run_id=scheduled__2024-12-19T00:00:00+00:00, execution_date=20241219T000000, start_date=20250525T051849, end_date=20250525T051911
[2025-05-25T05:19:12.378+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:19:12.817+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:19:12.866+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
