[2025-05-25T05:22:01.636+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:22:04.431+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-01-09T00:00:00+00:00 [queued]>
[2025-05-25T05:22:05.113+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-01-09T00:00:00+00:00 [queued]>
[2025-05-25T05:22:05.146+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:22:08.481+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_file> on 2025-01-09 00:00:00+00:00
[2025-05-25T05:22:09.330+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=460) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:22:10.091+0000] {standard_task_runner.py:72} INFO - Started process 531 to run task
[2025-05-25T05:22:09.909+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'generate_file', 'scheduled__2025-01-09T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpczcv6m_g']
[2025-05-25T05:22:10.584+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask generate_file
[2025-05-25T05:22:32.291+0000] {job.py:229} INFO - Heartbeat recovered after 36.53 seconds
[2025-05-25T05:22:33.656+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.generate_file scheduled__2025-01-09T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:22:37.161+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='generate_file' AIRFLOW_CTX_EXECUTION_DATE='2025-01-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-09T00:00:00+00:00'
[2025-05-25T05:22:37.173+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:22:37.926+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-25T05:22:38.256+0000] {job.py:229} INFO - Heartbeat recovered after 24.11 seconds
[2025-05-25T05:22:38.352+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:22:38.354+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=generate_file, run_id=scheduled__2025-01-09T00:00:00+00:00, execution_date=20250109T000000, start_date=20250525T052204, end_date=20250525T052238
[2025-05-25T05:22:38.870+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:22:39.132+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:22:39.159+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
