[2025-05-25T05:25:05.044+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:25:05.569+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-15T00:00:00+00:00 [queued]>
[2025-05-25T05:25:05.969+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-15T00:00:00+00:00 [queued]>
[2025-05-25T05:25:05.984+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:25:06.853+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): move_data_file> on 2025-01-15 00:00:00+00:00
[2025-05-25T05:25:07.143+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=670) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:25:07.173+0000] {standard_task_runner.py:72} INFO - Started process 729 to run task
[2025-05-25T05:25:07.128+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'move_data_file', 'scheduled__2025-01-15T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpao8l26vl']
[2025-05-25T05:25:07.206+0000] {standard_task_runner.py:105} INFO - Job 81: Subtask move_data_file
[2025-05-25T05:25:12.688+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-15T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:25:14.362+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='move_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-15T00:00:00+00:00'
[2025-05-25T05:25:14.414+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:25:15.092+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-25T05:25:15.204+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /tmp/processed_data/ && mv /tmp/data.csv /tmp/processed_data/']
[2025-05-25T05:25:15.996+0000] {subprocess.py:99} INFO - Output:
[2025-05-25T05:25:16.183+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-25T05:25:17.235+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:25:17.396+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=move_data_file, run_id=scheduled__2025-01-15T00:00:00+00:00, execution_date=20250115T000000, start_date=20250525T052505, end_date=20250525T052517
[2025-05-25T05:25:18.515+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:25:18.628+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
