[2025-05-25T05:22:15.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:22:17.826+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-05-25T05:22:18.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-05-25T05:22:18.400+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:22:20.252+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): move_data_file> on 2025-01-04 00:00:00+00:00
[2025-05-25T05:22:21.128+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:22:21.230+0000] {standard_task_runner.py:72} INFO - Started process 543 to run task
[2025-05-25T05:22:21.490+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'move_data_file', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpgbeuusk9']
[2025-05-25T05:22:21.849+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask move_data_file
[2025-05-25T05:22:27.541+0000] {job.py:229} INFO - Heartbeat recovered after 16.58 seconds
[2025-05-25T05:22:39.596+0000] {job.py:229} INFO - Heartbeat recovered after 12.21 seconds
[2025-05-25T05:22:40.783+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.move_data_file scheduled__2025-01-04T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:22:43.552+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='move_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-05-25T05:22:43.559+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:22:43.870+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-25T05:22:44.099+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /tmp/processed_data/ && mv /tmp/data.csv /tmp/processed_data/']
[2025-05-25T05:22:44.459+0000] {subprocess.py:99} INFO - Output:
[2025-05-25T05:22:44.540+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-25T05:22:45.400+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:22:45.415+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=move_data_file, run_id=scheduled__2025-01-04T00:00:00+00:00, execution_date=20250104T000000, start_date=20250525T052217, end_date=20250525T052245
[2025-05-25T05:22:45.900+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:22:46.486+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:22:46.536+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
