[2025-06-10T18:45:00.083+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-15T15:05:25.657+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-15T15:05:41.553+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: data_synth.card scheduled__2025-06-05T18:30:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-06-15T15:05:41.713+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
