[2025-05-25T05:30:31.070+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:30:31.421+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-02-23T00:00:00+00:00 [queued]>
[2025-05-25T05:30:32.005+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.move_data_file scheduled__2025-02-23T00:00:00+00:00 [queued]>
[2025-05-25T05:30:32.023+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:30:32.406+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): move_data_file> on 2025-02-23 00:00:00+00:00
[2025-05-25T05:30:32.480+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:30:32.533+0000] {standard_task_runner.py:72} INFO - Started process 1182 to run task
[2025-05-25T05:30:32.498+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'move_data_file', 'scheduled__2025-02-23T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmp7hr3_jh4']
[2025-05-25T05:30:32.580+0000] {standard_task_runner.py:105} INFO - Job 164: Subtask move_data_file
[2025-05-25T05:30:39.305+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.move_data_file scheduled__2025-02-23T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:30:41.750+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='move_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-23T00:00:00+00:00'
[2025-05-25T05:30:41.816+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:30:42.529+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-25T05:30:42.634+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p /tmp/processed_data/ && mv /tmp/data.csv /tmp/processed_data/']
[2025-05-25T05:30:43.316+0000] {subprocess.py:99} INFO - Output:
[2025-05-25T05:30:43.611+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-25T05:30:44.612+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:30:44.623+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=move_data_file, run_id=scheduled__2025-02-23T00:00:00+00:00, execution_date=20250223T000000, start_date=20250525T053031, end_date=20250525T053044
[2025-05-25T05:30:45.005+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:30:45.132+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
